### ISSUE TITLE
JQLite version possible?

### ISSUE THREAD

**Issue by PaulL1** [VersifitTechnologies/angular-ui-tab-scroll#1]
I'm interested in using this or a similar control (such as https://github.com/mikejacobson/angular-bootstrap-scrolling-tabs).  But I'd prefer not to have a JQuery dependency, my project is all angular and JQLite.  

It looks like only the "toTheRight" and "toTheLeft" functions really use jQuery.  Is it plausible they could be updated to use JQLite?  Is that something you have interest in / need for (I suspect the answer is no), or would you have any tips or suggestions if I were to fork and modify it myself?

**Comment by seiyria** [comment]
Yes, this would be fine, provided the original functionality was retained. We currently do not need something like this, but if you submitted a pull request, I'd accept it.

You could probably find the equivalent vanilla JS functions for the jquery functionality, since it seems like it's only used in toTheLeft and toTheRight (as you said).

**Comment by PaulL1** [comment]
I also see only mousedown/mouseup, not touchstart and touchend.  Does it work well on touch devices?  I know many emulate the mouse events, so perhaps you don't need touch events?

Further, getting my head around what it does - the tooltip seems to be the thing that requires jQuery, but the tooltip is also influencing the enabling of the left and right buttons.  So I could perhaps (for my purposes) end up with something much simpler if I didn't need the tooltips.

**Comment by seiyria** [comment]
I have honestly never tested it on touchscreen devices. This is only in use in one place in our app so far, and mobile users won't ever go there, probably. If you wanted to do some recognition to determine the proper event to bind, I wouldn't be opposed.

Yes, essentially whether or not there is a tooltip determines the visibility of the buttons. It's a coupling I'm not happy to have, but this solution had to happen within a short timeframe, so improvements are welcome. :D

**Comment by Shemesh** [comment]
@PaulL1 the latest versions do not use jQuery at all, the jQuery dependency was removed!
