### ISSUE TITLE
bower.json is not updated

### ISSUE THREAD

**Issue by Shemesh** [VersifitTechnologies/angular-ui-tab-scroll#12]
hi,
i have downloaded 0.1.4 zip and looking inside the bower.json there are some fields that need an update:
the version should be updated from 0.1.0 to 0.1.4
and the dependencies should be: larger than... instead of a specific version.

**Comment by Shemesh** [comment]
p.s.
in the dependencies i guess "angular-bootstrap" you mean ""angular-ui-bootstrap"

**Comment by seiyria** [comment]
`angular-bootstrap` is perfectly valid.
![](http://i.imgur.com/f3j0sa1.png)

**Comment by smithk58** [comment]
Released a new version and upated the bower.json accordingly.
