### ISSUE TITLE
Column with filter not work on IE

### ISSUE THREAD

**Issue by lecoleco** [VersifitTechnologies/angular-ui-tab-scroll#2]
Hi,

I put one option on grid to show or not the filter on column, i set on start all columns enableFiltering: false, and after selection of a column which i what to show the filter, I remove the column set enableFiltering = true and put column again. this work but only in safari and chrome not working IE 10.

If i click another option of menu and click again on the same page, the column show perfect.

What i have to do for this work like safari and chrome?

http://plnkr.co/edit/S0ymCr9S5mQ6UVqBSK7A?p=preview

Thanks

**Comment by seiyria** [comment]
Hi, 

I don't think this is the right project for what you're working on, sorry. This is specifically for usage with the angular-ui tab control; nothing more. You seem to have a table of sorts.
