### ISSUE TITLE
Error: [ngTransclude:orphan]

### ISSUE THREAD

**Issue by gieboyz** [VersifitTechnologies/angular-ui-tab-scroll#25]
Hi. i try to implement your library in my project, but when i implement it. always show error [ngTrsanclude:orphan] and my tab not showing.

But if i add "replace:true" in directive this error still shown on my console, but all working fine. can you explain to me how to fix this issue?? thanks.

**Comment by Shemesh** [comment]
hi,
in order to help you and find the issue i need more information:
1) what version of angular-ui-tab-scroll are you using?
2) please provide an example simple project, you can use http://plnkr.co/

**Comment by gieboyz** [comment]
Hi.
1. i use this version
/*
- angular-ui-tab-scroll
- https://github.com/VersifitTechnologies/angular-ui-tab-scroll
  *
- Version: 1.2.2
- License: MIT
  */
1. i try to provide, but still not working now, if already i will send it to you. But i will try describe it.

i modify your code with adding replace:true in directive function. and working but in console i got error, FYI i try to implement tab and ui-grid at the same time, 

![screenshot-localhost 2015-12-21 09-41-36](https://cloud.githubusercontent.com/assets/9793593/11922196/4eed81a0-a7c7-11e5-918f-fea3e78538f6.png)

![untitled2](https://cloud.githubusercontent.com/assets/9793593/11922275/3f42ee38-a7c8-11e5-9865-2b467b20787c.png)

this is error in console.
![untitled](https://cloud.githubusercontent.com/assets/9793593/11922191/41570336-a7c7-11e5-8d64-4a77f4dfbaac.png)

i hope this will explain it to you

**Comment by Shemesh** [comment]
sorry, i need more information, i cannot help by this description only. a working sample is the only way i can help.
1. the replace:true was **deprecated** in angular 1.3.0
2. are you sure it is coming from the tab-scroll? and not from something else?

**Comment by Shemesh** [comment]
@gieboyz - any news? or can i close this issue?

**Comment by Shemesh** [comment]
closing.
