### ISSUE TITLE
Nested tabsets

### ISSUE THREAD

**Issue by mattkees** [VersifitTechnologies/angular-ui-tab-scroll#26]
Any chance you'd be interested in extending this to work with nested tabsets?

We have an application with two nested tabsets that both need this scrolling functionality.  This component works great for one tabset but not so much with another scrolling tabset nested inside.

Thanks

**Comment by Shemesh** [comment]
i'm about to publish a major version (in a day or two), can you wait for it?

**Comment by mattkees** [comment]
Yeah, that's no problem.  I was able to change it a bit to make nested tabs work, but I'm sure my method isn't very robust.  ;)  I'll take a look at the new version.

I'll expose my noobness and attach my updated file:
[angular-ui-tab-scroll.txt](https://github.com/VersifitTechnologies/angular-ui-tab-scroll/files/86288/angular-ui-tab-scroll.txt)

It assumes the following (differentiating the nested tabsets via classes):
  <scrollable-tabset class="tabset1">
    <uib-tabset class="ui-tab tabset1">
      <scrollable-tabset class="tabset2">
        <uib-tabset class="ui-tab tabset2">
        </uib-tabset>
      </scrollable-tabset>
    </uib-tabset>
  </scrollable-tabset>

**Comment by Shemesh** [comment]
please use the latest version - 2.0.0 - and see if it works for you.
if still not please send a demo.

**Comment by Shemesh** [comment]
hi, @mattkees 
i have just released a new version - 2.1.0 - that will fix the nested tabs scroll issue

**Comment by eschnaath** [comment]
scrollable-tabset within the first toplevel scrollable-tabset works great.
scrollable-tabset within other (2nd, 3rd, ... last) toplevel scrollable-tabset does not display left/right/down scrolling arrows.
This issue can be recreated by modifying the demo (on plunker, for example).

**Comment by Shemesh** [comment]
seems like this is happening only if upon init the inner tabset are not inside the active tab = not visible.
this is working - http://plnkr.co/edit/hXxZz2?p=preview
but if you un-comment the first topmost tab, than the inner tabsets does truly **don't** have scrolls.
i'm guessing it happens because it is not yet calculated on screen.
at the time being you need to somehow call initiate a recalculation, you can either use the API, or force a window resize event.

**Comment by Shemesh** [comment]
after some researching...
i'm avoiding adding any watchers, so my best answer is you initiate a recalculation by either using the API doRecalculate() function, or forcing a window resize event.

**Comment by saranadmin** [comment]
Hi,

Usage of api in example code is not working as expected. Clicking "Scroll into Tab Index 6" is not selecting 6th Tab. Please advise.
