### ISSUE TITLE
Angular UI Bootstrap controls used are depricated

### ISSUE THREAD

**Issue by yohangz** [VersifitTechnologies/angular-ui-tab-scroll#28]
In this library you guys have used older syntax of UI Bootstrap. Latest UI bootstrap new syntax has `uib` prefix. Any plans of updating the library with latest syntax?

<img width="882" alt="screen shot 2016-01-24 at 5 52 17 pm" src="https://cloud.githubusercontent.com/assets/5279079/12536185/4bfc8538-c2c3-11e5-8c8e-cca5b058312e.png">

**Comment by Shemesh** [comment]
hi, @yohangz 
it is on my to-do list, hopefully soon.

**Comment by yohangz** [comment]
Great news. I'll keep track. Thanks in advance. :)

**Comment by yohangz** [comment]
Any update on this?

**Comment by Shemesh** [comment]
latest version - 2.2.0: upgrade UI Bootstrap to 0.14.x.
