### ISSUE TITLE
scrollIntoView : alignWithTop 

### ISSUE THREAD

**Issue by picolo74** [VersifitTechnologies/angular-ui-tab-scroll#33]
Hi,

scrollIntoView align the scrollable ancestor (top or bottom), this behavior is not really good when the page has a scrollbar.

check this plunker : http://plnkr.co/edit/fwFrfYGJkAwezqphog5A?p=preview 

Click on an element in the drop-down, the tab will be align to top.

**Comment by Shemesh** [comment]
version 2.2.1 fix this.
