### ISSUE TITLE
Error occurs when using attribute `heading`

### ISSUE THREAD

**Issue by Michel73** [VersifitTechnologies/angular-ui-tab-scroll#36]
I got an error when I'm using the attribute `heading` in element `uib-tab`. 

```
TypeError: Cannot read property 'textContent' of undefined
    at http://localhost:63342/scrolltabs/bower_components/angular-ui-tab-scroll/angular-ui-tab-scroll.js:297:92
    at Object.forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.js:341:20)
    at Scope.link.$scope.reCalcAll (http://localhost:63342/scrolltabs/bower_components/angular-ui-tab-scroll/angular-ui-tab-scroll.js:291:27)
```

If I using the element `uib-tab-heading` instead it works.

**Comment by Shemesh** [comment]
hi,
that is expected, since the change in [ui bootstrap v0.14.0](http://angular-ui.github.io/bootstrap/versioned-docs/0.14.0/) a "uib" prefix was addded

http://angular-ui.github.io/bootstrap/versioned-docs/0.14.0/#/tabs
what is the issue?

**Comment by Michel73** [comment]
The error occurs if I use:

```
<uib-tab heading="First tab">
        <div class="tabContent">First tab content</div>
</uib-tab>
```

The `heading` attribute is documented as an alternative to `<uib-tab-heading>`-tag.

**Comment by Shemesh** [comment]
please see if the latest code solved this and let me know.

**Comment by Michel73** [comment]
Ok, the latest code works for me.
