### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by saranadmin** [VersifitTechnologies/angular-ui-tab-scroll#42]
Hi,

Usage of api in example code is not working as expected. Clicking "Scroll into Tab Index 6" is not selecting 6th Tab (see here : http://embed.plnkr.co/YJNDaQ/). Please advise.

**Comment by saranadmin** [comment]
Can anyone help to solve the issue.

**Comment by Shemesh** [comment]
the selection of tabs should be managed by you, by using the uib-tabset properties.
the tab-scroll is not managing selection in any way.
