### ISSUE TITLE
Programatically selecting a tab at an index

### ISSUE THREAD

**Issue by saranadmin** [VersifitTechnologies/angular-ui-tab-scroll#43]
@Shemesh

Hi,

I am a beginner in this field. Can you please advise how to select a tab at an index when a particular event happens.

Thanks you

**Comment by Shemesh** [comment]
please read the bootstrap documentation --> go to [ui-bootstrap website](http://angular-ui.github.io/bootstrap/), select your version in 'previous docs', than read the docs for the tabset.
it is all in there.
