### ISSUE TITLE
When switching buildings, the floor of the button does not appear

### ISSUE THREAD

**Issue by imlove** [VersifitTechnologies/angular-ui-tab-scroll#44]
When switching buildings, the floor of the button does not appear
![qq 20160402111635](https://cloud.githubusercontent.com/assets/9476540/14224139/717805a8-f8c4-11e5-993d-535e5ee5fd53.png)

**Comment by Shemesh** [comment]
sorry i do not understand your meaning.

**Comment by imlove** [comment]
The first row in the picture are buildings, the second row are floors, When I switch building and the floor of the building is too much，but the second row without button like first row.

**Comment by Shemesh** [comment]
sorry, again,  i do not understand your meaning.
please write a demo code on https://plnkr.co/
