### ISSUE TITLE
Using api for nested tabset

### ISSUE THREAD

**Issue by saranadmin** [VersifitTechnologies/angular-ui-tab-scroll#45]
Hi,

I have tried API service on a single tabset and is working fine, but when working with nested tabset it is not. Here is my code.

`<scrollable-tabset api="scrlTabsApi" tooltip-left-placement="top">
    <uib-tabset style="height: 300px">
      <uib-tab ng-repeat="tab in tabs">
        <uib-tab-heading>{{tab.heading}}</uib-tab-heading>
        <div class="tabContent">
                {{tab}}
                <scrollable-tabset api="scrlTabsApi" tooltip-left-placement="top">
                    <uib-tabset style="height: 300px">
                        <uib-tab ng-repeat="tab in tabs">
                            <uib-tab-heading>{{tab.heading}}</uib-tab-heading>
                            <div class="tabContent">
                            Inner {{tab}}                           
                            </div>
                        </uib-tab>
                    </uib-tabset>
                </scrollable-tabset>
                </div>
      </uib-tab>
    </uib-tabset>
  </scrollable-tabset>`

 Please find that I am using api attribute in both outer and inner scrollable-tabset tags. How can I use api only for inner scrollable-tabset.

**Comment by Shemesh** [comment]
you simply use different api for each tabset, see example - http://plnkr.co/edit/Z3yzhtutEODimF4CHGyW?p=preview

**Comment by saranadmin** [comment]
Thank you
