### ISSUE TITLE
Restrict switching to other tab

### ISSUE THREAD

**Issue by saranadmin** [VersifitTechnologies/angular-ui-tab-scroll#46]
Is there any way to restrict switching to other tab after checking any condition. I have added a function in ng-click of tab and tried event.preventDefault(); but not working.

**Comment by Shemesh** [comment]
hi, @saranadmin 
this as well you should do with the tabset directly, not with the tab-scroll.
once again - go to the tabset doc to find what you need.
please ask here questions regarding the tab-scroll only.
