### ISSUE TITLE
Tab scroll on mouse scroll event

### ISSUE THREAD

**Issue by saranadmin** [VersifitTechnologies/angular-ui-tab-scroll#47]
Hi,

Is there any way to make tab scroll on mouse scroll event on tab. I did not see any options in documentation.

**Comment by Shemesh** [comment]
do you mean to use mouse scroll instead of the scroll left\right buttons?

**Comment by saranadmin** [comment]
Yes, Actually I need both left/right buttons and mouse scroll. Is that possible?

**Comment by saranadmin** [comment]
Any update on this.

**Comment by Shemesh** [comment]
this would be very weird behavior, talking usability, an unexpected and surprising behavior.
scrolling the mouse will do a horizontal scroll? - i've never seen such thing.
i think this is a bad usability.

**Comment by saranadmin** [comment]
Hi,

I think this is possible using jquery-mousewheel plugin.

You can see this usability in normal jquery scroll tab plugins here : http://joshreed.github.io/jQuery-ScrollTabs/

**Comment by Shemesh** [comment]
after looking again, and also looking at the sample you sent, i still stand in my opinion - horizontal scroll by using the mouse wheel is a bad usability! it is confusing and unexpected.
sorry - i will not add it to this package.

if, after all, you still feel that you need this feature you can fork and add it yourself.
