### ISSUE TITLE
uib-tabset type="pills"

### ISSUE THREAD

**Issue by knightjdr** [VersifitTechnologies/angular-ui-tab-scroll#49]
Great plugin and I have it working nicely. However, there doesn't seem to be support for pills. If I add type="pills" to uib-tabset, my pills stack. I can simply style my tabs to look like pills, so it isn't a major issue but if there is a simple fix, it would be a nice feature.

**Comment by Shemesh** [comment]
as you said "can simply style"... pills are just a different style.
but you can also make it work by searching all "nav-tabs" in the code and change them to "nav-pills".

the preferred solution is make your own style by overriding with your own css.
