### ISSUE TITLE
Scrollable tabset not work with ui-bootstrap-tpls-1.3.3.js

### ISSUE THREAD

**Issue by blotkevin** [VersifitTechnologies/angular-ui-tab-scroll#51]
Hi,

We can not use scrollable tabset with the latest ui-bootstrap-tpls-1.3.3.js. Do you have any solutions to this?

Thank you, 

Kevin

**Comment by GeroldSchierholz** [comment]
just change: 
`tab.active = true;`

 to 
`tab.select();`

on line 211 - see my pull request #50 

Best Regards

Gerold

**Comment by Shemesh** [comment]
fixed.
pull request #50 merged into version 2.2.6
