### ISSUE TITLE
not able to perform Scroll to tab view

### ISSUE THREAD

**Issue by chandanwankhade** [VersifitTechnologies/angular-ui-tab-scroll#52]
I am calling this function but not working for me.
$scope.main.scrollTabIntoView(i);

please let me know what steps to be followed while using this function.
my requirement is to set active state to particular tab. let me know if another method is available or any solution for my requirement.

Thank you

**Comment by Shemesh** [comment]
hi @chandanwankhade,
i'm not sure why it is not working for you, take a look at the example to see how to use.
it works perfectly fine.

**Comment by chandanwankhade** [comment]
thanks Shemesh,
 Its working. !! :)

**Comment by chandanwankhade** [comment]
I am expecting 
on calling $scope.main.scrollTabIntoView(i); the selected Tab must be in active state and that is not happening in demo file too. could you please help me how to perform this with angular-ui-tab-scroll?

**Comment by Shemesh** [comment]
as the function name imply - it is scrolling only, not selecting.
the selection of tabs have to be managed by you.
