### ISSUE TITLE
Failed to parse SourceMap: http://[...]/angular-ui-tab-scroll.css.map

### ISSUE THREAD

**Issue by pparavicini** [VersifitTechnologies/angular-ui-tab-scroll#53]
Thanks for a nifty library.  This is a bit of a nitpicking defect report, though likely easy to fix.

The following line at the bottom of angular-ui-tab-scroll.css:

/*# sourceMappingURL=angular-ui-tab-scroll.css.map */

causes the spurious error above, at least on the chrome console. 

This does not affect the functionality or greatness of the library, nor is it apparent to the end-user, but it chagrins those obsessive-compulsive amongst us who like to keep spurious errors out of our debug consoles.

It would be great if you could either remove the sourceMappingURL hint above in the distro, or add the angular-ui-tab-scroll.css.map file to the distro.

Thanks again for a nice component.

**Comment by Shemesh** [comment]
removed the sourceMappingURL  in v2.2.9
