### ISSUE TITLE
Feature Request: Add none tab items in the dropdown list

### ISSUE THREAD

**Issue by randellhodges** [VersifitTechnologies/angular-ui-tab-scroll#58]
I'd like to be able to add a few custom options in the dropdown list. For example, add a "Add" and "Delete" option. Is there a way to do it now, or is that something that'd need to be implemented?

**Comment by Shemesh** [comment]
opened in excellent timing, as me too needed this :-)
added this functionality in v2.3.0, see "drop-down-header-template-url"
also updated the demo so you can see it working.

**Comment by randellhodges** [comment]
Thanks! This might be better suited for a different feature request, but, is there a way to always render the dropdown button? I was trying to be clever use what you added for this to display a new tab button. Of course, if I don't have enough tabs to render the dropdown, it never gets create, thus the user can't create a tab.

I might revisit my design to place the button elsewhere, but thought it would be good there since that is a mostly dedicated space in the UI.

**Comment by Shemesh** [comment]
i see, this is indeed a different scenario - what you actually want is to display the drop-down **always**, right?

**Comment by randellhodges** [comment]
Not open, but the button that you click to open the dropdown, aka the button with the down arrow.

After revisiting my idea, I decided to adjust my UI so I don't need this functionality.
